commands/misc.py
commands/print_tools.py
migrations/env.py

Fix travis errors by reformatting base files

Run black to fix formatting errors

---

commands/misc.py

Add !haskell

---

commands/tex.py

Add amsmath to tex rendering

---

apollo.py
commands/blacklist.py
commands/print_tools.py
commands/reminders.py
commands/verify.py
karma/karma.py

Prevent database errors from locking up apollo.

Prevent database commit errors from locking up the 

---

commands/misc.py

Update servers to reflect new server versions

Update server info

---

apollo.py

Removed obsolete verification info and added link to Apollo's repo,

Updated help text

---

cogs/commands/widen.py

Make widen work with replies

---

karma/karma.py

I think this was left in accidentally following a merge

Remove errant else block

---

cogs/welcome.py
karma/karma.py

Left over in bf63c592669f14dbe58e2f0c09f79102ae44b392

Remove remaining references to the intros channel

---

cogs/commands/roll.py
roll/exceptions.py

Excessive dice rolls now get the proper error message

Fixed another error message bug

---

cogs/commands/misc.py

I tried to use a git command and it didn't do anything. Problems need answers.

Git command

---

cogs/commands/quotes.py

removed pointless if statement

---

apollo.py
cogs/commands/roomsearch.py

Connects to some of the Warwick APIs to fetch room info
Could do more, but most others require auth or SSO pain

Adds command to search for Warwick room quickly

---

cogs/commands/roomsearch.py

Resolves #97 
Also removed the duplicate entries for MSB from the API

Fixes error in room search when capacity was unavailable

---

apollo.py
cogs/channel_checker.py
config.example.yaml
config/config.py

Addresses #104. This checks for text channels, and reports on which text channels they were moved between -- position is strange for category and voice channels, so only considering text channels as that is where most of the problems are

Channel order checker, addresses #104

---

apollo.py
cogs/channel_checker.py
cogs/commands/admin.py
cogs/commands/blacklist.py
cogs/commands/counting.py
cogs/commands/date.py
cogs/commands/fact.py
cogs/commands/flip.py
cogs/commands/karma.py
cogs/commands/lcalc.py
cogs/commands/misc.py
cogs/commands/print_tools.py
cogs/commands/quotes.py
cogs/commands/reminders.py
cogs/commands/roll.py
cogs/commands/roomsearch.py
cogs/commands/say.py
cogs/commands/tex.py
cogs/commands/verify.py
cogs/commands/widen.py
cogs/database.py
cogs/irc.py
cogs/parallelism.py
cogs/welcome.py
config.example.yaml
config/config.py
requirements.txt
utils/utils.py

Hybrid slash commands for (almost) everything 😎 
(I still don't understand command syncing)

Update to Dpy 2.0

---

Dockerfile
docker-compose.yml

Makes it a bit easier to set up a dev environment, and is being used to streamline production deployment

Added Dockerfile

---

cogs/commands/flip.py

Closes issue #139.
Added the ability to add weights to provided options passed as arguments. The keyword "weights" separates the options and weights in the supplied arguments. The number of options must match the number of weights.

Feature/Extended flip for option weights.

---

cogs/commands/dalle.py

people wanted this also currenlty responsible for the most cursed line of python ever written
also responsivle for the 2nd time i have found a use for haskell (map my beloved)

now retains image history

---

cogs/commands/misc.py

should change the message for go

---

cogs/commands/reminders.py

127 I don't think is possible? I found this part of discord's documentation which shows why : https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups
143 I've essentially ported over the code from announcements.

looked into #127 and #143

---

cogs/commands/quotes.py

Addresses https://github.com/UWCS/apollo/issues/93 and https://github.com/UWCS/apollo/issues/94

Quote improvements PR 2

---

cogs/commands/tex.py

- Fix for #146
- Now works with one or more colours
- Slight quality drop but nothing serious

Fixed !tex color handling #146

---

cogs/commands/tex.py

Fixes #186 
Handles invalid equations

!tex error handling fix #186

---

cogs/commands/chatgpt.py
cogs/commands/quotes.py
utils/utils.py

Fixes #183 
`!karma reasons` handles it by creating a temp file to attach - need to figure out if this actually gets saved to file system or not

Message split not truncate

---

karma/karma.py

Remove thanks and sorry messages to break karma bots

Break karma botting

---

cogs/commands/karma.py

Fix minus sign issue

---

cogs/commands/karma.py

This is also fixed by adding xkcd context. 
Closes #204

Fix legend formatting

---

cogs/commands/vote.py
voting/discord_interfaces/discord_base.py
voting/vote_types/base_vote.py

- Deletes old votes
- Fixes some db issues
- Move command from !vote basic to just !vote since we don't have options atm.

Few fixes to vote

---

cogs/commands/run.py
config.example.yaml
config/config.py

- Added a single command, !run, that runs code within a code block in a message
- Added config parameter for pyromaniac API backend

Add !run command to run code using Pyromaniac backend

---

cogs/commands/birthday.py
cogs/commands/openaiadmin.py

made code for birthday and openai admin better
also added birthdy leaderboard and updated cooldown

refactored openaiadmin and users

---

apollo.py
cogs/commands/market.py
cogs/commands/onmessage.py

Market making

---

cogs/commands/market.py

Displayed market positions better as per #274

---

cogs/commands/market.py

Created boolean `open` in Market()
Bids and asks only go through if the market is open
Updated __str__ method to include whether the market is open or closed

Added close market fuctionality as per #276
